/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoiaRouteImport } from './routes/soia'
import { Route as IndexRouteImport } from './routes/index'

const SoiaRoute = SoiaRouteImport.update({
  id: '/soia',
  path: '/soia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/soia': typeof SoiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/soia': typeof SoiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/soia': typeof SoiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/soia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/soia'
  id: '__root__' | '/' | '/soia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SoiaRoute: typeof SoiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soia': {
      id: '/soia'
      path: '/soia'
      fullPath: '/soia'
      preLoaderRoute: typeof SoiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SoiaRoute: SoiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
